package hxo:component;

interface hxo-handler {
    record render-options {
        minify: bool,
        source-map: bool,
    }

    render: func(template: string, options: render-options) -> result<string, string>;
}

world hxo-world {
    export hxo-handler;
}
